# Generated by Django 2.1.2 on 2018-12-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20181210_1918'),
        ('dashboard', '0012_auto_20181210_1933'),
    ]

    operations = [
    ]
