# Generated by Django 2.1.2 on 2018-12-10 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_merge_20181210_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelannouncements',
            name='isDeleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='importantcontacts',
            name='isDeleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='medicalannouncements',
            name='isDeleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='messages',
            name='isDeleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='messannouncements',
            name='isDeleted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='hostelannouncements',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 15, 26, 1, 162161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicalannouncements',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 15, 26, 1, 163474, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messannouncements',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 15, 26, 1, 162775, tzinfo=utc)),
        ),
    ]
