# Generated by Django 2.1.2 on 2018-12-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20181210_2056'),
        ('dashboard', '0015_auto_20181210_2129'),
    ]

    operations = [
    ]
