# Generated by Django 2.1.2 on 2018-11-15 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_integration', '0003_auto_20181115_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('specialisation', models.CharField(blank=True, max_length=45, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_till', models.TimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 11, 15, 14, 38, 45, 104060, tzinfo=utc))),
                ('created_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('delete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField(blank=True, null=True)),
                ('problem', models.TextField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(default='M', max_length=5)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 11, 15, 14, 38, 45, 105265, tzinfo=utc))),
                ('created_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('delete', models.BooleanField(default=0)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medical.Doctors')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_integration.Student')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_from', models.DateField(blank=True, null=True)),
                ('leave_to', models.DateField(blank=True, null=True)),
                ('hometown', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2018, 11, 15, 14, 38, 45, 103411, tzinfo=utc))),
                ('created_at', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=45, null=True)),
                ('modified_at', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=45, null=True)),
                ('delete', models.BooleanField(default=0)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_integration.Student')),
            ],
        ),
    ]
