# Generated by Django 2.1.2 on 2018-11-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='gender',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
