# Generated by Django 2.1.2 on 2018-11-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20181109_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalappointment',
            name='gender',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
