# Generated by Django 2.1.2 on 2018-11-16 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20181115_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='medicalappointment',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='medicalleave',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 552317, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 553142, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicalleave',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 551484, tzinfo=utc)),
        ),
    ]
