# Generated by Django 2.1.2 on 2018-12-10 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_auto_20181210_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 7, 46, 36, 223747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 7, 46, 36, 223747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicalleave',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 7, 46, 36, 222747, tzinfo=utc)),
        ),
    ]
