# Generated by Django 2.1.2 on 2018-10-24 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_complaintregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintregister',
            name='comp_img',
            field=models.ImageField(default=datetime.datetime(2018, 10, 24, 17, 24, 55, 801304), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='idcomplaint_register',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
