# Generated by Django 2.1.2 on 2018-11-16 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_auto_20181115_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintregister',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='courrier',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='hostelleave',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='selfhelpgroup',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-11-16 11:17:18.584777'),
        ),
        migrations.AlterField(
            model_name='complaintregister',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 584841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 585715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hostelleave',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 584038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='selfhelpgroup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 587497, tzinfo=utc)),
        ),
    ]
