# Generated by Django 2.1.2 on 2018-10-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_auto_20181024_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintregister',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-10-24 19:23:56.732366'),
        ),
        migrations.AlterField(
            model_name='courrier',
            name='idcourrier',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
