# Generated by Django 2.1.2 on 2018-11-15 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0004_auto_20181115_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 15, 14, 43, 52, 44783, tzinfo=utc)),
        ),
    ]
