# Generated by Django 2.1.2 on 2018-11-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0002_logged_in_users'),
        ('api_integration', '0009_auto_20181116_1117'),
    ]

    operations = [
    ]
