# Generated by Django 2.1.2 on 2018-12-10 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0009_auto_20181116_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 13, 48, 57, 478744, tzinfo=utc)),
        ),
    ]
