# Generated by Django 2.1.2 on 2018-12-09 19:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0010_merge_20181116_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logged_in_users',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 19, 18, 2, 191045, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='logged_in_users',
        ),
    ]
