# Generated by Django 2.1.2 on 2018-12-10 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0019_auto_20181210_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 15, 59, 43, 951233, tzinfo=utc)),
        ),
    ]
