# Generated by Django 2.1.2 on 2018-12-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0018_merge_20181210_2055'),
        ('api_integration', '0020_auto_20181210_2129'),
    ]

    operations = [
    ]
