# Generated by Django 2.1.2 on 2018-10-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(default='media/images/default.png', upload_to='media/images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
