-- MySQL Script generated by MySQL Workbench
-- Thu Oct 11 11:20:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema its_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema its_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `its_test` DEFAULT CHARACTER SET latin1 ;
USE `its_test` ;

-- -----------------------------------------------------
-- Table `its_test`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`student` (
  `idstudent` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `roll` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idstudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`mess_refund`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`mess_refund` (
  `idmess_refund` INT NOT NULL,
  `mess_refund_amt` FLOAT NULL,
  `student_id` INT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idmess_refund`),
  INDEX `mess_refund_idx` (`student_id` ASC),
  CONSTRAINT `mess_refund`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`mess_leave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`mess_leave` (
  `idmess_leave` INT NOT NULL,
  `mess_leave_from` DATE NULL,
  `mess_leave_to` DATE NULL,
  `student_id` INT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idmess_leave`),
  INDEX `mess_leave_idx` (`student_id` ASC),
  CONSTRAINT `mess_leave`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`food_quality_feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`food_quality_feedback` (
  `idfood_quality_feedback` INT NOT NULL,
  `feedback` VARCHAR(200) NULL,
  `student_id` INT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idfood_quality_feedback`),
  INDEX `mess_feedback_idx` (`student_id` ASC),
  CONSTRAINT `mess_feedback`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`mess_announcements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`mess_announcements` (
  `idmess_announcements` INT NOT NULL,
  `announcement` VARCHAR(500) NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idmess_announcements`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`doctor_and_hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`doctor_and_hospital` (
  `iddoctor_and_hospital` INT NOT NULL,
  `doctor_name` VARCHAR(45) NULL,
  `hospital_name` VARCHAR(45) NULL,
  `speciality` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`iddoctor_and_hospital`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`medical_appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`medical_appointments` (
  `idmedical_appointments` INT NOT NULL,
  `appointment_time` DATETIME NULL,
  `student_id` INT NULL,
  `doctor_id` INT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idmedical_appointments`),
  INDEX `apooint_doctor_idx` (`doctor_id` ASC),
  INDEX `appoint_student_idx` (`student_id` ASC),
  CONSTRAINT `appoint_doctor`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `its_test`.`doctor_and_hospital` (`iddoctor_and_hospital`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `appoint_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`medical_leave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`medical_leave` (
  `idmedical_leave` INT NOT NULL,
  `medical_leave_from` DATE NULL,
  `medical_leave_to` DATE NULL,
  `student_id` INT NULL,
  `home_town` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idmedical_leave`),
  INDEX `medical_leave_idx` (`student_id` ASC),
  CONSTRAINT `medical_leave`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`items` (
  `iditems` INT NOT NULL,
  `item_name` VARCHAR(45) NULL,
  `cost` FLOAT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`iditems`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`order_items` (
  `idorder_items` INT NOT NULL,
  `student_id` INT NULL,
  `item_id` INT NULL,
  `quantity` INT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idorder_items`),
  INDEX `item_order_idx` (`item_id` ASC),
  INDEX `student_item_idx` (`student_id` ASC),
  CONSTRAINT `item_order`
    FOREIGN KEY (`item_id`)
    REFERENCES `its_test`.`items` (`iditems`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `student_item`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`hostel_announcements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`hostel_announcements` (
  `id_announcements` INT NOT NULL,
  `announcement` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`id_announcements`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`restaurant` (
  `idrestaurant` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `rating` INT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idrestaurant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`menu` (
  `idmenu` INT NOT NULL,
  `food_item` VARCHAR(45) NULL,
  `restaurant_id` INT NULL,
  `cost` INT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idmenu`),
  INDEX `restaurant_menu_idx` (`restaurant_id` ASC),
  CONSTRAINT `restaurant_menu`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `its_test`.`restaurant` (`idrestaurant`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`food_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`food_order` (
  `idfood_order` INT NOT NULL,
  `student_id` INT NULL,
  `food_id` INT NULL,
  `quantity` INT NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idfood_order`),
  INDEX `student_food_idx` (`student_id` ASC),
  INDEX `food_item_idx` (`food_id` ASC),
  CONSTRAINT `student_food`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `food_item`
    FOREIGN KEY (`food_id`)
    REFERENCES `its_test`.`menu` (`idmenu`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`complaint_register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`complaint_register` (
  `idcomplaint_register` INT NOT NULL,
  `complaint` VARCHAR(200) NULL,
  `student_id` INT NULL,
  `room_no` INT NULL,
  `completed` INT NULL DEFAULT 0,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idcomplaint_register`),
  INDEX `complaint_idx` (`student_id` ASC),
  CONSTRAINT `complaint`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`private_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`private_message` (
  `idprivate_message` INT NOT NULL,
  `message` VARCHAR(500) NULL,
  `student_id_hash` VARCHAR(25) NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idprivate_message`),
  INDEX `message_private_idx` (`student_id_hash` ASC),
  CONSTRAINT `message_private`
    FOREIGN KEY (`student_id_hash`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`courrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`courrier` (
  `idcourrier` INT NOT NULL,
  `courrier_ref_no` VARCHAR(45) NULL,
  `delivery_agent` VARCHAR(45) NULL,
  `student_id` INT NULL,
  `courrier_company` VARCHAR(45) NULL,
  `expected_arrival_time` DATETIME NULL,
  `timestamp` DATETIME NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idcourrier`),
  INDEX `courrier_idx` (`student_id` ASC),
  CONSTRAINT `courrier`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`logs` (
  `idlogs` INT NOT NULL,
  `timestamp` DATETIME NULL,
  `log` VARCHAR(45) NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idlogs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `its_test`.`Non-Anonymous Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `its_test`.`Non-Anonymous Chat` (
  `idNon-Anonymous Chat` INT NOT NULL,
  `student_id` INT NULL,
  `message` VARCHAR(45) NULL,
  `created_at` DATE NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_at` DATE NULL,
  `modified_by` VARCHAR(45) NULL,
  PRIMARY KEY (`idNon-Anonymous Chat`),
  INDEX `non-anonymous_idx` (`student_id` ASC),
  CONSTRAINT `non-anonymous`
    FOREIGN KEY (`student_id`)
    REFERENCES `its_test`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
