# Generated by Django 2.1.2 on 2018-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_type',
            field=models.CharField(max_length=45),
        ),
    ]
