# Generated by Django 2.1.2 on 2018-10-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=45)),
                ('order_type', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
