# Generated by Django 2.1.2 on 2018-12-09 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181210_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 19, 19, 32, 440115, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='manualorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 19, 19, 32, 441114, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 19, 19, 32, 444116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 9, 19, 19, 32, 443115, tzinfo=utc)),
        ),
    ]
