# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-24 06:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessAnnouncements',
        ),
    ]
