# Generated by Django 2.1.2 on 2018-11-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messrefund',
            name='ref_amount',
        ),
        migrations.RemoveField(
            model_name='messrefund',
            name='refund_from',
        ),
        migrations.RemoveField(
            model_name='messrefund',
            name='refund_to',
        ),
        migrations.RemoveField(
            model_name='messrefund',
            name='student',
        ),
        migrations.AddField(
            model_name='messrefund',
            name='mess_leave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mess.MessLeave'),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-11-03 00:24:02.971706'),
        ),
    ]
