# Generated by Django 2.1.2 on 2018-11-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_auto_20181103_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='messleave',
            name='ref_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-11-03 02:33:05.465399'),
        ),
    ]
