# Generated by Django 2.1.2 on 2018-11-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_auto_20181103_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messrefund',
            name='mess_leave',
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-11-03 13:01:12.904368'),
        ),
    ]
