# Generated by Django 2.1.2 on 2018-11-16 05:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_auto_20181115_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messfeedback',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='messitems',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='messleave',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='messrefund',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='orderhistorymess',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.RenameField(
            model_name='orderlistmess',
            old_name='delete',
            new_name='isDeleted',
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-11-16 11:17:18.640888'),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 640936, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messleave',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 637072, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messrefund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 637861, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderhistorymess',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 639133, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderlistmess',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 16, 5, 47, 18, 639912, tzinfo=utc)),
        ),
    ]
