# Generated by Django 2.1.2 on 2018-10-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_messfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-10-25 15:09:41.990416'),
        ),
    ]
