# Generated by Django 2.1.2 on 2018-11-03 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_integration', '0002_auto_20181103_1323'),
        ('mess', '0004_auto_20181103_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='messrefund',
            name='refund_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messrefund',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api_integration.Student'),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-11-03 13:23:41.199151'),
        ),
    ]
