# Generated by Django 2.1.2 on 2018-11-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_auto_20181109_2002'),
        ('mess', '0005_auto_20181116_1117'),
    ]

    operations = [
    ]
