# Generated by Django 2.1.2 on 2018-10-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0006_auto_20181025_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-10-25 22:43:07.333354'),
        ),
    ]
