# Generated by Django 2.1.2 on 2018-12-10 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_auto_20181210_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-12-10 13:16:36.239737'),
        ),
        migrations.AlterField(
            model_name='messfeedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 7, 46, 36, 239737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messleave',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 7, 46, 36, 234741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messrefund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 7, 46, 36, 235741, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderhistorymess',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 7, 46, 36, 237738, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderlistmess',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 10, 7, 46, 36, 238738, tzinfo=utc)),
        ),
    ]
