# Generated by Django 2.1.2 on 2018-10-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0008_auto_20181026_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfeedback',
            name='comp_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/2018-10-27 22:06:18.370261'),
        ),
    ]
